apollo_msgs/ApolloperceptioninferenceAnchorBox[] anchorbox
float32[] thresholds
float32 orientationscale 0.0
float32 dimensionscale 0.0
float32 frontscale 0.0
float32 rearscale 0.0
uint32 objectscale
uint32 noobjectscale
float32 classscale
uint32 coordscale
float32 jitter
float32 bias
bool rescore
uint32 numclasses
bool biasmatch
float32 threshold
uint32 trickyiter 400
bool usel1loss false
bool usetwicesoftmax false
bool isanchornormalized false
bool[] orienable
string anchorfile "anchor.txt"
bool usesideboxv2 false
bool usesideboxv3 false
int32 oricycle 1
