float64 interpolateddeltas 0.1
int32 reanchoringtrailsnum 50
float64 reanchoringposstddev 0.25
float64 reanchoringlengthstddev 1.0
bool estimatebound false
float64 defaultbound 2.0
float64 vehicleshortestdimension 1.04
apollo_msgs/ApolloplanningFemPosDeviationSmootherConfig femposdeviationsmootherconfig
float64 collisiondecreaseratio 0.9
float64 maxforwardv 2.0
float64 maxreversev 2.0
float64 maxforwardacc 3.0
float64 maxreverseacc 2.0
float64 maxaccjerk 4.0
float64 deltat 0.2
apollo_msgs/ApolloplanningPiecewiseJerkSpeedOptimizerConfig scurveconfig
