string cameradev
string frameid
string pixelformat "yuyv"
int32 iomethod#ApollodriverssmartereyeconfigIOMethod
uint32 width
uint32 height
uint32 framerate
bool monochrome false
int32 brightness -1
int32 contrast -1
int32 saturation -1
int32 sharpness -1
int32 gain -1
bool autofocus false
int32 focus -1
bool autoexposure true
int32 exposure 100
bool autowhitebalance true
int32 whitebalance 4000
uint32 bytesperpixel 3
uint32 triggerinternal 0
uint32 triggerfps 30
string channelname
string channelnameimage
string channelnameimagecompressed
uint32 devicewaitms 2000
uint32 spinrate 200
int32 outputtype#ApollodriverssmartereyeconfigOutputType
int32 compressconf#ApollodriverssmartereyeconfigCompressConfig
