float32 velocitythreshold 2.0
int32 velocityoutputdelay 2
apollo_msgs/ApolloperceptioncameraomtKalmanParam worldcenter
apollo_msgs/ApolloperceptioncameraomtKalmanParam imagecenter
float32 imagewhupdaterate
int32 worldlhwhistory 15
float32 heightdiffratio 0.1
int32 worldstatehistory 30
int32 mincachedworldstatehistorysize 5
int32 mincachedvelocitysize 10
int32 mincachedpositionsize 25
int32 calcavgpositionwindowsize 7
float32 staticspeedthreshold 0.5
float32 staticspeedthresholdped 0.3
float32 minmovingavgspeed 1.0
float32 minmovingavgspeedped 0.5
float32 abnormalaccthreshold 6.0
float32 abnormalaccthresholdped 3.0
float32 abnormalvelocityheadinganglethreshold
bool clappingvelocity false
int32 worldmeanvelocityduration 10
int32 trackedlife 3
float32 typefiltervar 0.3
float32 largevelocityratio 2.5
float32 toolargevelocityratio 1.5
int32 meanfilterwindow 10
float32 directionfilterratio 0.7
float32 displacementthetavar 0.25
float32 velocitythetavar 0.5
float32 stablemovingspeed 2.0
