string cameranames "front_6mm,front_12mm"
string inputcamerachannelnames
float64 timestampoffset 0.0
string cameraobstacleperceptionconfdir
string cameraobstacleperceptionconffile
int32 framecapacity 20
int32 imagechannelnum 3
bool enableundistortion false
bool enablevisualization false
string outputobstacleschannelname
string cameraperceptionvizmessagechannelname
string prefusedchannelname
float64 defaultcamerapitch 0.0
float64 defaultcameraheight 1.5
string lanecalibrationworkingsensorname
string calibratormethod "LaneLineCalibrator"
string calibservicename
bool runcalibservice true
bool outputcameradebugmsg false
string cameradebugchannelname
float64 tsdiff 0.1
bool outputfinalobstacles false
string visualdebugfolder "/apollo/debug_output"
string visualcamera "front_6mm"
bool writevisualimg false
float64 minlanelinelengthforcipv 2
float64 averagelanewidthinmeter 3.7
float64 maxvehiclewidthinmeter 2.5
float64 averageframerate 0.05
bool imagebasedcipv false
int32 debuglevel 0
bool enablecipv false
string lidartype "velodyne128"
