string cameranames "front_6mm,front_12mm"
string inputcamerachannelnames
float64 timestampoffset 0.0
string cameralaneperceptionconfdir
string cameralaneperceptionconffile "lane.pt"
int32 framecapacity 20
int32 imagechannelnum 3
bool enableundistortion false
bool enablevisualization false
string outputlaneschannelname
float64 defaultcamerapitch 0.0
float64 defaultcameraheight 1.5
string lanecalibrationworkingsensorname
string calibratormethod "LaneLineCalibrator"
string calibservicename
bool runcalibservice true
float64 tsdiff 0.1
string visualdebugfolder "/apollo/debug_output"
string visualcamera "front_6mm"
bool writevisualimg false
