bool maxdistancevalid false
bool sensoridvalid false
bool radarpowervalid false
bool outputtypevalid true
bool sendqualityvalid true
bool sendextinfovalid true
bool sortindexvalid false
bool storeinnvmvalid true
bool ctrlrelayvalid false
bool rcsthresholdvalid true
uint32 maxdistance 248
uint32 sensorid 0
int32 outputtype#ApollodriversracobitRadarOutputType
uint32 radarpower 0
uint32 ctrlrelay 0
bool sendextinfo true
bool sendquality true
uint32 sortindex 0
uint32 storeinnvm 1
int32 rcsthreshold#ApollodriversracobitRadarRcsThreshold
