float64 s 0.0
float64 t 0.0
float64 v 0.0
float64 speedlimit 0.0
float64 acc 0.0
float64 jerk 0.0
apollo_msgs/ApolloplanningautotuningObstacleFeature[] followobsfeature
apollo_msgs/ApolloplanningautotuningObstacleFeature[] overtakeobsfeature
apollo_msgs/ApolloplanningautotuningObstacleFeature[] nudgeobsfeature
apollo_msgs/ApolloplanningautotuningObstacleFeature[] stopobsfeature
int32 collisiontimes 0
apollo_msgs/ApolloplanningautotuningObstacleFeature[] virtualobsfeature
float64 lateralacc 0.0
float64 pathcurvatureabs 0.0
apollo_msgs/ApolloplanningautotuningObstacleFeature[] sidepassfrontobsfeature
apollo_msgs/ApolloplanningautotuningObstacleFeature[] sidepassrearobsfeature
