float32 gridradius 80.0
float32 heightthreshold 2.5
float32 partitioncellsize 1.0
float32 vehiclefiltercellsize 0.3
float32 pedestrianfiltercellsize 0.1
float32 outlierlength 0.1
float32 outlierwidth 0.1
float32 outlierheight 0.3
uint32 outlierminnumpoints 3
string grounddetector
string roifilter "HdmapROIFilter"
bool removegroundpoints true
bool removeroi true
bool doclassification true
apollo_msgs/ApolloperceptionlidarNCutParam ncutparam
