apollo_msgs/ApolloperceptioninferenceAnchorBox[] anchorbox
float32[] thresholds
float32 orientationscale 0.0
uint32 objectscale
uint32 noobjectscale
uint32 classscale
uint32 coordscale
float32 jitter
float32 bias
bool rescore
uint32 numclasses
bool biasmatch
float32 threshold
uint32 trickyiter 400
apollo_msgs/ApolloperceptioninferenceNonMaximumSuppressionParameter nmsparam
int32 keeptopk -1
float32 posthreshold
float32 negthreshold
int32 negratio 3
