uint32 numoutput
bool biasterm true
uint32[] pad
uint32[] kernelsize
uint32[] stride
uint32[] dilation
uint32 padh 0
uint32 padw 0
uint32 kernelh
uint32 kernelw
uint32 strideh
uint32 stridew
uint32 group 1
apollo_msgs/ApolloperceptioninferenceFillerParameter weightfiller
apollo_msgs/ApolloperceptioninferenceFillerParameter biasfiller
int32 engine#ApolloperceptioninferenceEngine
int32 axis 1
bool forcendim2col false
