uint32 udpport
string frameid
string pixelformat "yuyv"
uint32 record
uint32 width
uint32 height
uint32 framerate
bool monochrome false
int32 brightness -1
int32 contrast -1
int32 saturation -1
int32 sharpness -1
int32 gain -1
bool autofocus false
int32 focus -1
bool autoexposure true
int32 exposure 100
bool autowhitebalance true
int32 whitebalance 4000
uint32 bytesperpixel 3
string triggerparam "f2ff"
uint32 metricerrorcode 11
int32 fpgadevnumber -1
int32 cameraseqnumber -1
int32 compressconf#ApollodriversvideoconfigCompressConfig
