float64 minlanemarkerquality 0.5
int32 lanesource#ApollorelativeMapLaneSource
float64 maxlenfromnavigationline 250.0
float64 minlenfornavigationlane 150.0
float64 maxlenfornavigationlane 250.0
float64 rationavigationlanelentospeed 8.0
float64 maxdistancetonavigationline 15.0
float64 minviewrangetouselanemarker 0.5
float64 minlanehalfwidth 1.5
float64 maxlanehalfwidth 2.0
float64 lanemarkerweight 0.1
